### ISSUE TITLE
Settings option to disable Week In Review surveys

### ISSUE THREAD

**Issue by lvaschmidt** [nkalupahana/baseline#188]
Some users (me) are here for the journaling and not for all of the features. It would be nice if as the feature set expands certain features could be optional as not all users will need all components. 

Currently if you hit remind me later the prompt just keeps popping up.

![image](https://user-images.githubusercontent.com/42920104/188223430-a516b3a2-5732-47a2-b0d7-fe6dbae0a709.png)

**Comment by nkalupahana** [comment]
Fair enough, okay. I'll add a setting to disable it; that should be out next week. (I highly recommend doing Week In Review, though -- it just takes a few minutes each week, and a lot of people have found it to be useful!)

**Comment by nkalupahana** [comment]
Until then, if you email your UID (user ID, in settings) to privacy@getbaseline.app, we can manually skip your Week In Review for this week so you won't see the prompt anymore :)

**Comment by nkalupahana** [comment]
A feature to accomplish this is planned to be added within the next month. I've disabled your Week in Review until then. Thanks so much for reporting!

**Comment by nkalupahana** [comment]
Feature is in! Should enter beta in a few days, and go public in a week or so after that.
