### ISSUE TITLE
About Topics

### ISSUE THREAD

**Issue by abaines-nextup** [nkalupahana/baseline#315]
Please consider updating your `About` `Topics` to include items like `mood-tracker` `mood-journal` `android` `ios` `tracker` `mood-tracking` `journaling`. Might help you show up in [searches like this 🔎](https://github.com/search?q=mood-tracker+OR+moodtracker+OR+mood-journal+OR+mood-tracking+in%3Atopics&type=repositories&s=stars&o=desc&p=1). 

Hopefully an easy win — Best of luck 😀

**Comment by nkalupahana** [comment]
Thanks! Just added :)
