### ISSUE TITLE
Missing data is treated as 0 instead of N/A in mood graph

### ISSUE THREAD

**Issue by MicahRus** [nkalupahana/baseline#324]
This may be more of a discussion than an issue. But to me it doesn't make sense for missing data in the mood graph to be filled as 0. This creates weird looking data when failing to track mood for even just 1 day but more importantly it isn't a true reflection on my mood for that day. 

I would suggest to treat missing data as N/A.
I would also suggest to have some indication on the graph of when it is missing data (Grayed out, different colour, different pattern, etc)

**Comment by nkalupahana** [comment]
I'm sorry, I'm not sure I understand. On the mood graph, when you log a 0, you get a blue dot on the center line. When you don't log anything, there's nothing there (no dots at all). That's different, right? More clarification would be great, thanks.

**Comment by MicahRus** [comment]
Hopefully these images can help clarify what I'm talking about. 

To me it seems like missing days, the data is being set to 0. Whereas i think it would be more correct to mark the data as n/a. 
![Screenshot_20240106_221958_baseline](https://github.com/nkalupahana/baseline/assets/59851519/44f9fe04-7a75-4019-87bb-22c738b1e68c)
![Screenshot_20240106_221947_baseline](https://github.com/nkalupahana/baseline/assets/59851519/75ee6d16-c9d0-4221-8baf-faf37d8bb7a3)
![Screenshot_20240106_221857_baseline](https://github.com/nkalupahana/baseline/assets/59851519/4a8dd781-bf31-403a-b5cb-705531d7f156)


As you can see in the images I have no entries from the 9th of September onwards, but the data is reflecting those days as being a 0. Where I think they should be ungraded as it makes the mood look worse or better than it was.

**Comment by nkalupahana** [comment]
Oh, yes! Good news -- this was fixed in a PR last week and is currently in beta. Expect the fix to be rolled out soon.
