### ISSUE TITLE
Cannot log in: Sorry, but we need you to log in one more time.

### ISSUE THREAD

**Issue by Dustie** [nkalupahana/baseline#401]
I just installed the app and tried to login with Google. I am stuck in a "Sorry, but we need you to log in one more time" loop while "Getting encryption keys". I've tried the web version on the same phone and I was able to log in and write an entry. However doing so still didn't allow me to log in via the app.

**Phone**:
Stock Google Pixel 7, android 14, latest update.

**What I've tried**:
I have tried to log in 15+ times. Tried the web version. Tried restarting the app. Tried mobile data instead of WiFi. Tried deleting app data and force close.

**Comment by nkalupahana** [comment]
Hi! That error only shows up when Google gives insufficient permissions to baseline, and should only happen on sign-up (i.e. should never happen if you've already signed in on web). Very strange bug, thanks for reporting. 

@Dustie could you try signing in on the app again, and then immediately comment here? That'll allow us to sync our logs with the timestamp and debug your sign-in attempt. Thank you!

**Comment by Dustie** [comment]
Of course. Just tried again a few times.

**Comment by nkalupahana** [comment]
@Dustie It looks like somehow, you've given baseline insufficient scopes to access your Google Account, but only on the app (i.e. the app is giving an access token with different scopes than have been requested), and isn't refreshing despite the mismatch. There are two things I would try:
1. Uninstall baseline, restart your phone, reinstall, and try signing in again.
2. Go to [https://myaccount.google.com/connections](https://myaccount.google.com/connections) and revoke baseline's access permissions entirely. Then, try to sign in on the app. You should then get a permissions prompt -- make sure you allow baseline to access its own configuration files in Google Drive.

Sorry about this! Android phones have a lot of variability, and unfortunately stuff like this occasionally happens. We test on multiple models, including a Pixel, and somehow we haven't run into the failure before. Thanks for working with us to resolve it.

**Comment by Dustie** [comment]
Thanks for the steps. I have uninstalled the app and removed the permissions. Unfortunately it already had "See, create and delete its own configuration data in your Google Drive" permission and reinstall did not fix the problem. 

![Screenshot_20240922-004830](https://github.com/user-attachments/assets/ee72b799-8333-41e3-b2f0-942254f80838)

This is the permissions after reinstall (which are the same as before).

**Comment by Dustie** [comment]
Timestamp for log in attempt :-)

**Comment by nkalupahana** [comment]
Darn, okay. We're still seeing the "insufficient permissions" error on our end, so your phone must still be hanging onto its old access token. Let me take a look and see what we can do. 

Until then: 
- If you have an Apple ID or a different Google account, that will likely fix the problem. 
- We run a public beta program, which has a different Google auth token and thus might get you past this issue. If you want to try that, you can join [here.](https://dply.me/bxpdh9#install)
- You can use baseline on web, which is an admittedly worse experience, but it does work.

**Comment by nkalupahana** [comment]
@Dustie we may have identified the problem with sign-in. Would you mind installing this beta version of baseline, and then trying to sign in with Google?

To do this, uninstall your current version of baseline, and then click the link -- it should take you to the Play Store app.
[https://play.google.com/apps/test/RQKNaPRkd-M/ahAO29uNShaQay-FS6UYfO-xkiuAMUNapm2az9XfDIvINVc2rnqtWEGbQS3UURCEBlOvljOun8EETdyeRZmA6aM6p7](https://play.google.com/apps/test/RQKNaPRkd-M/ahAO29uNShaQay-FS6UYfO-xkiuAMUNapm2az9XfDIvINVc2rnqtWEGbQS3UURCEBlOvljOun8EETdyeRZmA6aM6p7)

**Comment by Dustie** [comment]
That fixed it 👍

**Comment by nkalupahana** [comment]
@Dustie the version on the Play Store now has this fix! We recommend switching to that so you continue getting app updates. Thanks so much for helping us test this and find a solution.
