### ISSUE TITLE
baseline Gap Fund

### ISSUE THREAD

**Issue by nkalupahana** [nkalupahana/baseline#44]
The gap fund has a couple components:

- [x] Form for submissions
- [x] System for donations
- [x] Function(?) to take submissions and log them
- [x] Fraud prevention -- need to use app for n days and have x mood logs
- [x] Some sort of documented process for ingesting submissions and distributing donations
- [x] Some sort of documented criteria for donations
- [x] Easy way to disable form remotely

**Comment by aadibajpai** [comment]
feature: I think an ethereum smart contract checks all the boxes here
